# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "643555ab4353a5100df5d550426ca871"
name = "customer-extension"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,read_orders,write_orders,read_products,read_inventory,read_fulfillments,write_fulfillments,read_shipping,read_locations,read_draft_orders,write_draft_orders,read_checkouts,write_checkouts,read_content,write_content,read_gift_cards,write_gift_cards,read_price_rules,write_price_rules,read_reports,read_analytics,read_marketing_events,write_marketing_events"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
