api_version = "2026-04"

[[extensions]]
name = "customer-extension"
handle = "customer-extension"
type = "ui_extension"
uid = "3392f465-f282-2a5a-b60e-29c1ee30432aae903e16"

[[extensions.targeting]]
module = "./src/OrderStatusBlock.jsx"
target = "customer-account.order-status.block.render"

[[extensions.targeting]]
module = "./src/OrderIndexBlock.jsx"
target = "customer-account.order-index.block.render"

[[extensions.targeting]]
module = "./src/ProfileBlock.jsx"
target = "customer-account.profile.block.render"

[[extensions.targeting]]
module = "./src/ProfileAnnouncement.jsx"
target = "customer-account.profile.announcement.render"

[extensions.capabilities]
api_access = true
