export function CountrySelect({ label, value, onChange }) {
  return (
    <s-select label={label} value={value} onChange={onChange}>
      <s-option value="">— Select country —</s-option>
      <s-option value="AF">Afghanistan</s-option>
      <s-option value="AL">Albania</s-option>
      <s-option value="DZ">Algeria</s-option>
      <s-option value="AR">Argentina</s-option>
      <s-option value="AU">Australia</s-option>
      <s-option value="AT">Austria</s-option>
      <s-option value="BE">Belgium</s-option>
      <s-option value="BR">Brazil</s-option>
      <s-option value="CA">Canada</s-option>
      <s-option value="CL">Chile</s-option>
      <s-option value="CN">China</s-option>
      <s-option value="CO">Colombia</s-option>
      <s-option value="HR">Croatia</s-option>
      <s-option value="CZ">Czech Republic</s-option>
      <s-option value="DK">Denmark</s-option>
      <s-option value="EG">Egypt</s-option>
      <s-option value="FI">Finland</s-option>
      <s-option value="FR">France</s-option>
      <s-option value="DE">Germany</s-option>
      <s-option value="GH">Ghana</s-option>
      <s-option value="GR">Greece</s-option>
      <s-option value="HK">Hong Kong</s-option>
      <s-option value="HU">Hungary</s-option>
      <s-option value="IN">India</s-option>
      <s-option value="ID">Indonesia</s-option>
      <s-option value="IE">Ireland</s-option>
      <s-option value="IL">Israel</s-option>
      <s-option value="IT">Italy</s-option>
      <s-option value="JP">Japan</s-option>
      <s-option value="JO">Jordan</s-option>
      <s-option value="KE">Kenya</s-option>
      <s-option value="MY">Malaysia</s-option>
      <s-option value="MX">Mexico</s-option>
      <s-option value="MA">Morocco</s-option>
      <s-option value="NL">Netherlands</s-option>
      <s-option value="NZ">New Zealand</s-option>
      <s-option value="NG">Nigeria</s-option>
      <s-option value="NO">Norway</s-option>
      <s-option value="PK">Pakistan</s-option>
      <s-option value="PE">Peru</s-option>
      <s-option value="PH">Philippines</s-option>
      <s-option value="PL">Poland</s-option>
      <s-option value="PT">Portugal</s-option>
      <s-option value="RO">Romania</s-option>
      <s-option value="RU">Russia</s-option>
      <s-option value="SA">Saudi Arabia</s-option>
      <s-option value="SG">Singapore</s-option>
      <s-option value="ZA">South Africa</s-option>
      <s-option value="KR">South Korea</s-option>
      <s-option value="ES">Spain</s-option>
      <s-option value="SE">Sweden</s-option>
      <s-option value="CH">Switzerland</s-option>
      <s-option value="TW">Taiwan</s-option>
      <s-option value="TH">Thailand</s-option>
      <s-option value="TR">Turkey</s-option>
      <s-option value="UA">Ukraine</s-option>
      <s-option value="AE">United Arab Emirates</s-option>
      <s-option value="GB">United Kingdom</s-option>
      <s-option value="US">United States</s-option>
      <s-option value="VN">Vietnam</s-option>
    </s-select>
  );
}

export function OriginCountrySelect({ label, value, onChange }) {
  return (
    <s-select label={label} value={value} onChange={onChange}>
      <s-option value="">Select an option...</s-option>
      <s-option value="Afghanistan">Afghanistan</s-option>
      <s-option value="Åland Islands">Åland Islands</s-option>
      <s-option value="Albania">Albania</s-option>
      <s-option value="Algeria">Algeria</s-option>
      <s-option value="Andorra">Andorra</s-option>
      <s-option value="Angola">Angola</s-option>
      <s-option value="Anguilla">Anguilla</s-option>
      <s-option value="Antigua & Barbuda">Antigua &amp; Barbuda</s-option>
      <s-option value="Argentina">Argentina</s-option>
      <s-option value="Armenia">Armenia</s-option>
      <s-option value="Aruba">Aruba</s-option>
      <s-option value="Ascension Island">Ascension Island</s-option>
      <s-option value="Australia">Australia</s-option>
      <s-option value="Austria">Austria</s-option>
      <s-option value="Azerbaijan">Azerbaijan</s-option>
      <s-option value="Bahamas">Bahamas</s-option>
      <s-option value="Bahrain">Bahrain</s-option>
      <s-option value="Bangladesh">Bangladesh</s-option>
      <s-option value="Barbados">Barbados</s-option>
      <s-option value="Belarus">Belarus</s-option>
      <s-option value="Belgium">Belgium</s-option>
      <s-option value="Belize">Belize</s-option>
      <s-option value="Benin">Benin</s-option>
      <s-option value="Bermuda">Bermuda</s-option>
      <s-option value="Bhutan">Bhutan</s-option>
      <s-option value="Bolivia">Bolivia</s-option>
      <s-option value="Bosnia & Herzegovina">Bosnia &amp; Herzegovina</s-option>
      <s-option value="Botswana">Botswana</s-option>
      <s-option value="Brazil">Brazil</s-option>
      <s-option value="British Indian Ocean Territory">British Indian Ocean Territory</s-option>
      <s-option value="British Virgin Islands">British Virgin Islands</s-option>
      <s-option value="Brunei">Brunei</s-option>
      <s-option value="Bulgaria">Bulgaria</s-option>
      <s-option value="Burkina Faso">Burkina Faso</s-option>
      <s-option value="Burundi">Burundi</s-option>
      <s-option value="Cambodia">Cambodia</s-option>
      <s-option value="Cameroon">Cameroon</s-option>
      <s-option value="Canada">Canada</s-option>
      <s-option value="Cape Verde">Cape Verde</s-option>
      <s-option value="Caribbean Netherlands">Caribbean Netherlands</s-option>
      <s-option value="Cayman Islands">Cayman Islands</s-option>
      <s-option value="Central African Republic">Central African Republic</s-option>
      <s-option value="Chad">Chad</s-option>
      <s-option value="Chile">Chile</s-option>
      <s-option value="China">China</s-option>
      <s-option value="Christmas Island">Christmas Island</s-option>
      <s-option value="Cocos (Keeling) Islands">Cocos (Keeling) Islands</s-option>
      <s-option value="Colombia">Colombia</s-option>
      <s-option value="Comoros">Comoros</s-option>
      <s-option value="Congo - Brazzaville">Congo - Brazzaville</s-option>
      <s-option value="Congo - Kinshasa">Congo - Kinshasa</s-option>
      <s-option value="Cook Islands">Cook Islands</s-option>
      <s-option value="Costa Rica">Costa Rica</s-option>
      <s-option value="Croatia">Croatia</s-option>
      <s-option value="Curaçao">Curaçao</s-option>
      <s-option value="Cyprus">Cyprus</s-option>
      <s-option value="Czechia">Czechia</s-option>
      <s-option value="Côte d'Ivoire">Côte d'Ivoire</s-option>
      <s-option value="Denmark">Denmark</s-option>
      <s-option value="Djibouti">Djibouti</s-option>
      <s-option value="Dominica">Dominica</s-option>
      <s-option value="Dominican Republic">Dominican Republic</s-option>
      <s-option value="Ecuador">Ecuador</s-option>
      <s-option value="Egypt">Egypt</s-option>
      <s-option value="El Salvador">El Salvador</s-option>
      <s-option value="Equatorial Guinea">Equatorial Guinea</s-option>
      <s-option value="Eritrea">Eritrea</s-option>
      <s-option value="Estonia">Estonia</s-option>
      <s-option value="Eswatini">Eswatini</s-option>
      <s-option value="Ethiopia">Ethiopia</s-option>
      <s-option value="Falkland Islands">Falkland Islands</s-option>
      <s-option value="Faroe Islands">Faroe Islands</s-option>
      <s-option value="Fiji">Fiji</s-option>
      <s-option value="Finland">Finland</s-option>
      <s-option value="France">France</s-option>
      <s-option value="French Guiana">French Guiana</s-option>
      <s-option value="French Polynesia">French Polynesia</s-option>
      <s-option value="French Southern Territories">French Southern Territories</s-option>
      <s-option value="Gabon">Gabon</s-option>
      <s-option value="Gambia">Gambia</s-option>
      <s-option value="Georgia">Georgia</s-option>
      <s-option value="Germany">Germany</s-option>
      <s-option value="Ghana">Ghana</s-option>
      <s-option value="Gibraltar">Gibraltar</s-option>
      <s-option value="Greece">Greece</s-option>
      <s-option value="Greenland">Greenland</s-option>
      <s-option value="Grenada">Grenada</s-option>
      <s-option value="Guadeloupe">Guadeloupe</s-option>
      <s-option value="Guatemala">Guatemala</s-option>
      <s-option value="Guernsey">Guernsey</s-option>
      <s-option value="Guinea">Guinea</s-option>
      <s-option value="Guinea-Bissau">Guinea-Bissau</s-option>
      <s-option value="Guyana">Guyana</s-option>
      <s-option value="Haiti">Haiti</s-option>
      <s-option value="Honduras">Honduras</s-option>
      <s-option value="Hong Kong SAR">Hong Kong SAR</s-option>
      <s-option value="Hungary">Hungary</s-option>
      <s-option value="Iceland">Iceland</s-option>
      <s-option value="India">India</s-option>
      <s-option value="Indonesia">Indonesia</s-option>
      <s-option value="Iraq">Iraq</s-option>
      <s-option value="Ireland">Ireland</s-option>
      <s-option value="Isle of Man">Isle of Man</s-option>
      <s-option value="Israel">Israel</s-option>
      <s-option value="Italy">Italy</s-option>
      <s-option value="Jamaica">Jamaica</s-option>
      <s-option value="Japan">Japan</s-option>
      <s-option value="Jersey">Jersey</s-option>
      <s-option value="Jordan">Jordan</s-option>
      <s-option value="Kazakhstan">Kazakhstan</s-option>
      <s-option value="Kenya">Kenya</s-option>
      <s-option value="Kiribati">Kiribati</s-option>
      <s-option value="Kosovo">Kosovo</s-option>
      <s-option value="Kuwait">Kuwait</s-option>
      <s-option value="Kyrgyzstan">Kyrgyzstan</s-option>
      <s-option value="Laos">Laos</s-option>
      <s-option value="Latvia">Latvia</s-option>
      <s-option value="Lebanon">Lebanon</s-option>
      <s-option value="Lesotho">Lesotho</s-option>
      <s-option value="Liberia">Liberia</s-option>
      <s-option value="Libya">Libya</s-option>
      <s-option value="Liechtenstein">Liechtenstein</s-option>
      <s-option value="Lithuania">Lithuania</s-option>
      <s-option value="Luxembourg">Luxembourg</s-option>
      <s-option value="Macao SAR">Macao SAR</s-option>
      <s-option value="Madagascar">Madagascar</s-option>
      <s-option value="Malawi">Malawi</s-option>
      <s-option value="Malaysia">Malaysia</s-option>
      <s-option value="Maldives">Maldives</s-option>
      <s-option value="Mali">Mali</s-option>
      <s-option value="Malta">Malta</s-option>
      <s-option value="Martinique">Martinique</s-option>
      <s-option value="Mauritania">Mauritania</s-option>
      <s-option value="Mauritius">Mauritius</s-option>
      <s-option value="Mayotte">Mayotte</s-option>
      <s-option value="Mexico">Mexico</s-option>
      <s-option value="Moldova">Moldova</s-option>
      <s-option value="Monaco">Monaco</s-option>
      <s-option value="Mongolia">Mongolia</s-option>
      <s-option value="Montenegro">Montenegro</s-option>
      <s-option value="Montserrat">Montserrat</s-option>
      <s-option value="Morocco">Morocco</s-option>
      <s-option value="Mozambique">Mozambique</s-option>
      <s-option value="Myanmar (Burma)">Myanmar (Burma)</s-option>
      <s-option value="Namibia">Namibia</s-option>
      <s-option value="Nauru">Nauru</s-option>
      <s-option value="Nepal">Nepal</s-option>
      <s-option value="Netherlands">Netherlands</s-option>
      <s-option value="New Caledonia">New Caledonia</s-option>
      <s-option value="New Zealand">New Zealand</s-option>
      <s-option value="Nicaragua">Nicaragua</s-option>
      <s-option value="Niger">Niger</s-option>
      <s-option value="Nigeria">Nigeria</s-option>
      <s-option value="Niue">Niue</s-option>
      <s-option value="Norfolk Island">Norfolk Island</s-option>
      <s-option value="North Macedonia">North Macedonia</s-option>
      <s-option value="Norway">Norway</s-option>
      <s-option value="Oman">Oman</s-option>
      <s-option value="Pakistan">Pakistan</s-option>
      <s-option value="Palestinian Territories">Palestinian Territories</s-option>
      <s-option value="Panama">Panama</s-option>
      <s-option value="Papua New Guinea">Papua New Guinea</s-option>
      <s-option value="Paraguay">Paraguay</s-option>
      <s-option value="Peru">Peru</s-option>
      <s-option value="Philippines">Philippines</s-option>
      <s-option value="Pitcairn Islands">Pitcairn Islands</s-option>
      <s-option value="Poland">Poland</s-option>
      <s-option value="Portugal">Portugal</s-option>
      <s-option value="Qatar">Qatar</s-option>
      <s-option value="Réunion">Réunion</s-option>
      <s-option value="Romania">Romania</s-option>
      <s-option value="Russia">Russia</s-option>
      <s-option value="Rwanda">Rwanda</s-option>
      <s-option value="Samoa">Samoa</s-option>
      <s-option value="San Marino">San Marino</s-option>
      <s-option value="São Tomé & Príncipe">São Tomé &amp; Príncipe</s-option>
      <s-option value="Saudi Arabia">Saudi Arabia</s-option>
      <s-option value="Senegal">Senegal</s-option>
      <s-option value="Serbia">Serbia</s-option>
      <s-option value="Seychelles">Seychelles</s-option>
      <s-option value="Sierra Leone">Sierra Leone</s-option>
      <s-option value="Singapore">Singapore</s-option>
      <s-option value="Sint Maarten">Sint Maarten</s-option>
      <s-option value="Slovakia">Slovakia</s-option>
      <s-option value="Slovenia">Slovenia</s-option>
      <s-option value="Solomon Islands">Solomon Islands</s-option>
      <s-option value="Somalia">Somalia</s-option>
      <s-option value="South Africa">South Africa</s-option>
      <s-option value="South Georgia & South Sandwich Islands">South Georgia &amp; South Sandwich Islands</s-option>
      <s-option value="South Korea">South Korea</s-option>
      <s-option value="South Sudan">South Sudan</s-option>
      <s-option value="Spain">Spain</s-option>
      <s-option value="Sri Lanka">Sri Lanka</s-option>
      <s-option value="St. Barthélemy">St. Barthélemy</s-option>
      <s-option value="St. Helena">St. Helena</s-option>
      <s-option value="St. Kitts & Nevis">St. Kitts &amp; Nevis</s-option>
      <s-option value="St. Lucia">St. Lucia</s-option>
      <s-option value="St. Martin">St. Martin</s-option>
      <s-option value="St. Pierre & Miquelon">St. Pierre &amp; Miquelon</s-option>
      <s-option value="St. Vincent & Grenadines">St. Vincent &amp; Grenadines</s-option>
      <s-option value="Sudan">Sudan</s-option>
      <s-option value="Suriname">Suriname</s-option>
      <s-option value="Svalbard & Jan Mayen">Svalbard &amp; Jan Mayen</s-option>
      <s-option value="Sweden">Sweden</s-option>
      <s-option value="Switzerland">Switzerland</s-option>
      <s-option value="Taiwan">Taiwan</s-option>
      <s-option value="Tajikistan">Tajikistan</s-option>
      <s-option value="Tanzania">Tanzania</s-option>
      <s-option value="Thailand">Thailand</s-option>
      <s-option value="Timor-Leste">Timor-Leste</s-option>
      <s-option value="Togo">Togo</s-option>
      <s-option value="Tokelau">Tokelau</s-option>
      <s-option value="Tonga">Tonga</s-option>
      <s-option value="Trinidad & Tobago">Trinidad &amp; Tobago</s-option>
      <s-option value="Tristan da Cunha">Tristan da Cunha</s-option>
      <s-option value="Tunisia">Tunisia</s-option>
      <s-option value="Turkey">Turkey</s-option>
      <s-option value="Turkmenistan">Turkmenistan</s-option>
      <s-option value="Turks & Caicos Islands">Turks &amp; Caicos Islands</s-option>
      <s-option value="Tuvalu">Tuvalu</s-option>
      <s-option value="U.S. Outlying Islands">U.S. Outlying Islands</s-option>
      <s-option value="Uganda">Uganda</s-option>
      <s-option value="Ukraine">Ukraine</s-option>
      <s-option value="United Arab Emirates">United Arab Emirates</s-option>
      <s-option value="United Kingdom">United Kingdom</s-option>
      <s-option value="United States">United States</s-option>
      <s-option value="Uruguay">Uruguay</s-option>
      <s-option value="Uzbekistan">Uzbekistan</s-option>
      <s-option value="Vanuatu">Vanuatu</s-option>
      <s-option value="Vatican City">Vatican City</s-option>
      <s-option value="Venezuela">Venezuela</s-option>
      <s-option value="Vietnam">Vietnam</s-option>
      <s-option value="Wallis & Futuna">Wallis &amp; Futuna</s-option>
      <s-option value="Western Sahara">Western Sahara</s-option>
      <s-option value="Yemen">Yemen</s-option>
      <s-option value="Zambia">Zambia</s-option>
      <s-option value="Zimbabwe">Zimbabwe</s-option>
    </s-select>
  );
}
